### PR TITLE
Feature/title favicon

### PR DESCRIPTION
**Pull request by collerhatguy**
## Description

https://www.loom.com/share/09e207abb351412d9f1d91500d04de35
- adds human rights first logo next to title
- adds more descriptive title

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by caralocke** [comment]
I think it looks great! Can't wait to see it in action. I love that you took the logo and made a favicon from it. Great job!

**Review by tdubs42 — CHANGES_REQUESTED** [review]
In order to have a robust and accessible site we want to ensure we align with best practices for favicons. [This](https://sympli.io/blog/heres-everything-you-need-to-know-about-favicons-in-2020/) is a great resource to explain the logic behind multiple favicon files.

[Here](https://favicon.io/favicon-converter/) is a great option that I use regularly for my personal projects 

After watching the Loom:
- Please use the logo provided by HRF and not a cropped version. Logos are often copyright / trademark works and should not be altered unless approved by the stakeholder. Also, for mobile devices we may want the full logo.

**Comment by tdubs42** [comment]
@caralocke make sure you get credit for your reviews by hitting either "approve" or "request changes" so it doesn't just post as a comment :)

**Review by RimshaSaleem — APPROVED** [review]
great job!

**Review by crayburn18 — CHANGES_REQUESTED** [review]
looks good, but seems that an alt prop is missing from the image

**Review by crayburn18 — APPROVED** [review]
everything looks good, image could use alt prop

**Review by caralocke — APPROVED** [review]
Just re-commenting to show approval.

**Comment by tdubs42** [comment]
@collerhatguy Please let me know if you would like to discuss any of the resources I shared with you :smile:

**Review by makeityourself121 — APPROVED** [review]
great job, getting it done before we forget to do it! 😊

**Review by madina-iz — APPROVED** [review]

**Comment by tdubs42** [comment]
I have not seen any progress on this PR today and am closing it due to the amount of work going on in this repo. I will be sure to have @collerhatguy assigned to that card once it is pulled out of the backlog and we can go over the resources I linked in my review.

**Pull request closed without merging**
