### PR TITLE
Feature/landing page

### PR DESCRIPTION
**Pull request by Andrewschaer**
## Description

Updated and cleaned up the the route tree for the application.  This included making the landing page the main route of the application and what the user will see when they log in.  This also included deprecating some previously included routes, pages, and components from the previous cohort that were unused (e.g. DocumentList, ExampleDataVis, ExampleList, Datavis, Home, and ProfileList, Stories). 

Authors:
Andrew Schaer
Tawnya Wessar
Bailey Evanger
Jesse Leegwater
Romy Shockey

<a href="https://www.loom.com/share/4990a7b47b224d2eaefe13f42b244dee">
    <p>Loom | Free Screen & Video Recording Software - Watch Video</p>
    
  </a>

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by rkshockey — APPROVED** [review]
The update looks good to me, it's simply rearranging some paths and deleting unused documents.

**Review by tdubs42 — APPROVED** [review]
It was so fun to be apart of this call and PR! Y'all showed amazing teamwork and communication to get this route tree cleaned up, unused files and directories deleted, and a shout out to Jesse for making us custom bookmark SVGs! I'll continue to say it: great work!

I will also point out we discovered the `format` script and that is why you may see files with slight formatting changes. FE and UX now know to run `format` before committing and pushing to keep consistent formatting :smile:

**Comment by tdubs42** [comment]
[Clean-up route tree and make landing page [ / ] route](https://trello.com/c/R5H9mm2A/101-clean-up-route-tree-and-make-landing-page-route)

**Review by crayburn18 — APPROVED** [review]
Good job cleaning up the code

**Review by RimshaSaleem — APPROVED** [review]
Good job!

**Pull request merged**
