### PR TITLE
Feature/header

### PR DESCRIPTION
**Pull request by Andrewschaer**
## Description

Built out the header bar that will be located at the top of the application and house the HRF logo, search bar, logout button and profile avatar logo.  This will be a very important component of the application as the search bar will be integral for use of finding documents.

Authors:
Juliane Vo Nguyen
Andrew Schaer
Rimsha Saleem
Ryan Ishimaru

<a href="https://www.loom.com/share/974298fb07bf4318bc3d9cc8f0b359af">
    <p>Loom | Free Screen & Video Recording Software - Watch Video</p>
    
  </a>

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by collerhatguy — CHANGES_REQUESTED** [review]
Unnecessary variables are imported into the header component. I make the same mistake all the time. should take 2 seconds to fix. Looks gorgeous though.

**Review by collerhatguy — APPROVED** [review]
It's ready spaghetti

**Review by rishimaru23 — APPROVED** [review]

**Review by crayburn18 — APPROVED** [review]
everything looks good no conflicts

**Review by makeityourself121 — APPROVED** [review]
Everything Looks great! try to resolve the merge conflict, except that looks good.

**Pull request merged**
