### PR TITLE
Feature/readme

### PR DESCRIPTION
**Pull request by nora-exe**
# Authors
@nora-exe @JackOrth 

## Description

Early push of revised FE Readme incl. Contributors to leave time to get all team info.

Adds team info (name, picture, GH & LinkedIn) with table template for adding more as needed.

Short Loom walkthrough [here](https://www.loom.com/share/a00a5089f78e405e90b5367e4b7d5d60).

## Type of change

- [x] Documentation
- [x] Markdown

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [     ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by JLeegwater — COMMENTED** [review]
Is this looking for approvals? It seems like it still needs more work from the Key Features down.

**Review by tdubs42 — APPROVED** [review]
Great work getting the contributors added, fleshing out sections for management and Lambda staff, and maintaining the styling! This was a very large and descriptive template, but as long as long as we keep updating it as we know more, this will be a GREAT source of truth for this app

**Review by JLeegwater — APPROVED** [review]
Good job figuring out the styling! When my group was doing the DS one, we were pretty confused with how to format the cards. Looks Good!

**Review by tdubs42 — APPROVED** [review]
These changes were done per request with TPM approval. We discussed how to make changes in a new branch moving forward. Looks good!

**Comment by nora-exe** [comment]
@JLeegwater Yep, the PR description points out this is just an initial push so Contributors can see if they're listed & info is correct:

`Early push` `to leave time to get all team info.`

Key features & onwards is still TBD and thus WIP.

**Comment by tdubs42** [comment]
[Update FE README](https://trello.com/c/DlZM0QLq/40-update-fe-readme)

**Review by JackOrth — APPROVED** [review]
This is a great initial push. It's great to have the contributors added. The organization and styling of it is well formatted, making the future updates for this file much more manageable.

**Review by collerhatguy — APPROVED** [review]
its ready spaghetti

**Review by rishimaru23 — APPROVED** [review]
looks great

**Review by RimshaSaleem — APPROVED** [review]

**Review by BradfordMez — APPROVED** [review]
ReadMe's Looking Great!

**Review by crayburn18 — APPROVED** [review]
good to go

**Pull request merged**
