### PR TITLE
Feature/tag popover

### PR DESCRIPTION
**Pull request by JLeegwater**
## Description

We built out a more advanced way of displaying tags. This change will be useful when a document has a lot of tags and or tags with names over 8 characters long. When there are a lot of tags, it will show as many as you specify and any tags leftover will be put in a popover on a "..." tag. This will also truncate any tags over 8 characters long and put the full name in a tooltip to display when the cursor hovers over the tag.

Authors:
Jesse Leegwater
Romy Shockey
Anwar Aldogmi
Jacob Shomali

https://www.loom.com/share/8722f2f575e043ad9be809476a634003

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by juliane1999 — APPROVED** [review]
A nice addition!

**Review by crayburn18 — APPROVED** [review]
Looks great, like the slice/tooltip feature for the tags.

**Review by makeityourself121 — APPROVED** [review]
Great job!

**Review by collerhatguy — APPROVED** [review]
I love looking through the everyones code and seeing how it was that they solved the problem of not having enough available space for all the tags in some cases. I noticed the key values were not being used properly (they are supposed to go on the outer most element) and that there was a simpler way to write the code that split the tags based on sized. Other than that the cake was magnificent and I just added frosting.

**Review by tdubs42 — APPROVED** [review]
Great solution for our tag problem, as well as really clean code! @paulstgermain can we please have this PR merged ASAP rocky :smiley:

**Review by bevanger — APPROVED** [review]
The code looks very clean and concise. Great job on solving the tag problem.

**Review by Andrewschaer — COMMENTED** [review]
This was a great usage of the tags provided by Ant Design.  Really like how adding it to our common components folder will allow future cohorts to be able to add in tags to future pages (e.g. a document view) with ease.  Very excited to see how this tags feature will continue to be improved for an even better UX!

**Pull request merged**
