### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by nora-exe**
## Description

Completed ReadMe template. This push added project `About`, `tech stack` stats, backend & DS credit, and `contribution guidelines`.

BE/DS info was added for cross-ref in case the FE readme is seen first.

[Loom](https://www.loom.com/share/ba6fa36cf10c4e0f99d5f1823d7645dd)

## Type of change

- documentation

## Checklist:

- [✔] My code follows the style guidelines of this project
- [✔] I have performed a self-review of my own code
- [N/A] I have removed unnecessary comments/console logs from my code
- [✔] I have made corresponding changes to the documentation if necessary (optional)
- [✔] My changes generate no new warnings
- [✔] I have checked my code and corrected any misspellings
- [✔] No duplicate code left within changed files
- [ N/A] Size of pull request kept to a minimum
- [✔] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by lucchesia7 — APPROVED** [review]
Love the implementation of linking the Readme's for FE and DS into your BE. This was a great idea. Changes to the documentation are clean and concise. Every point has a purpose. Great job here!

**Review by bevanger — APPROVED** [review]
Great job on adding detailed  descriptions of what Human Rights First and our product is. The features and tech stack look complete and written cleanly. Good job with the styling of everything.

**Review by JLeegwater — APPROVED** [review]
Great addition! Awesome that you linked the other repos this one relies on.

**Review by collerhatguy — APPROVED** [review]

**Review by BradfordMez — APPROVED** [review]
Looking Great! ReadMe is looking super organized!

**Review by caralocke — APPROVED** [review]
VERY well done! Every section looks well put together and I love that you added links to the Pat Finucane Centre and the Wikipedia for The Troubles. It definitely brings everything together.

**Review by fervelgo — APPROVED** [review]
Clear and clean. Love the links in "Our Product" section for context 😍 
Also the links referencing docs for the tech stack. Exquisiteee 👌🏼 

Looking great :)

**Pull request merged**
