### PR TITLE
Feature/landing card tests

### PR DESCRIPTION
**Pull request by collerhatguy**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)
https://www.loom.com/share/1e439ec20b6e4fe6b9f9c62148813323 
- added prop types to landing card to insure only the right data types are plugged into the component
- added jest tests that ensure that data given is properly rendered and re-rendered
- created mocks folder for mock data to be used in tests and to DRY the codebase

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by makeityourself121 — APPROVED** [review]
Great job @collerhatguy, implementing the tests, but try to fill in the descriptions section in your pull request.

**Review by rkshockey — APPROVED** [review]
Thank you so much for adding this, we were remiss in not including these tests ourselves. It looks like you've covered everything very thoroughly.

The mock doc object will be useful until we're pulling data from the backend as we build out the landing and search pages. Once we're communicating with backend it'll go down to just being used for testing.

Again, thank you so much for adding this.

**Review by caralocke — APPROVED** [review]
Thank you for doing this! I know we had talked about making tests for this when we built the component yesterday, so this is a huge help and it looks like you nailed testing all the things that should be tested!

**Comment by tdubs42** [comment]
[Tests for Card Doc Preview](https://trello.com/c/WSwfYFPI/78-tests-for-card-doc-preview)

**Comment by Andrewschaer** [comment]
This was an awesome update to the code base and will serve as a great resource for future cohorts to make sure any updates on the front end do not break the existing card functionality.  The tests are very detailed, and I particularly like the one to check the tags.  This may have to be updated as the tags feature gets updated over time, but for now it serves a great purpose!

**Review by Andrewschaer — COMMENTED** [review]
This was an awesome update to the code base and will serve as a great resource for future cohorts to make sure any updates on the front end do not break the existing card functionality. The tests are very detailed, and I particularly like the one to check the tags. This may have to be updated as the tags feature gets updated over time, but for now it serves a great purpose!

**Pull request merged**
