### PR TITLE
added wireframe and mockups

### PR DESCRIPTION
**Pull request by HeyAnwar**
##Coauthors
Ryan
Anwar
Juliane

## Description

Added the wireframe and mockups

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by JackOrth — COMMENTED** [review]
Thanks for adding these!

**Review by bevanger — APPROVED** [review]
Thank you for adding these, it will be very useful to have easy access to these files.

**Review by RimshaSaleem — APPROVED** [review]

**Review by collerhatguy — APPROVED** [review]
wireframes in the repo make it pretty convenient for future contributors so they don't have to save a separate link. I think it's a good idea.

**Comment by tdubs42** [comment]
[Save wireframes and mockups in FE repo in a "design" file for future reference](https://trello.com/c/PNQLV9HK/105-save-wireframes-and-mockups-in-fe-repo-in-a-design-file-for-future-reference)

**Pull request merged**
