### PR TITLE
Feature/ Global State

### PR DESCRIPTION
**Pull request by rkshockey**
## Description

This branch updates the repo to establish redux global state for the list of documents to be displayed. A reducer for documents and a few base actions were created, the actions currently return dummy data, pending the creation of an endpoint for us to access. The intent of this is to be a base for later features, allowing global state to be pulled to display either bookmarks or search results. This also sets the stage for one of our stretch features, where you can page through the list of documents from the expanded view.

Authors:
Romy Shockey
Jacob Shomali
Dharmik Savaliya

https://www.loom.com/share/03e8bb8f86854bc8b704ac54c39fb04d

Fixes # (issue)

Some misplaced code from the LandingCard feature was also moved to its proper place during the course of this work.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by caralocke — APPROVED** [review]
This looks really well done, easily legible and the overview of it is very thorough. Thank you!

**Review by lucchesia7 — APPROVED** [review]

**Review by bverfurth — CHANGES_REQUESTED** [review]
It looks good but you have a lint error

**Comment by rkshockey** [comment]
> It looks good but you have a lint error

Are you referring to the warning with UseEffect? Because I may need some help solved that, I've been unable to remove that error without causing an infinite loop.

**Review by juliane1999 — APPROVED** [review]
The redux implementation looks great and organized!

**Review by bverfurth — APPROVED** [review]

**Review by JLeegwater — APPROVED** [review]
Looks good! From my research, the linting error is more of a warning and always catches useEffects that have an empty dependency array for rendering on mount. There could be a better way to fix this, but from past experience it is ok to tell eslint to ignore these kinds of errors.

**Review by RimshaSaleem — APPROVED** [review]

**Review by crayburn18 — APPROVED** [review]
Code looks well organized and thought out

**Comment by tdubs42** [comment]
[Redux and Landing Card List](https://trello.com/c/kYtTVYAb/79-redux-and-landing-card-list)

**Review by collerhatguy — APPROVED** [review]
I love it

**Pull request merged**
