### PR TITLE
added research notes about authorization servers

### PR DESCRIPTION
**Pull request by bevanger**
## Description

I added my research notes on Okta Authorization Servers so that others in our team can have a better understanding of how our authorization server works easily without having to do their own research.

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/2a751441312c459dbee871a83ed4baaf?sharedAppSource=personal_library

### CODE REVIEW

**Review by bverfurth — APPROVED** [review]
Great work! This looks good.

**Review by tdubs42 — APPROVED** [review]
You went above and beyond owning this research. Thank you for putting this info into a doc

**Review by collerhatguy — APPROVED** [review]
Incredibly detailed. definitely handy to have around.

**Review by caralocke — APPROVED** [review]
This is extremely helpful information, thank you so much for this! Thank you for breaking everything down like this, it makes it very easy to find what's needed.

**Review by crayburn18 — APPROVED** [review]
Great work gathering the info

**Review by RimshaSaleem — APPROVED** [review]

**Review by madina-iz — APPROVED** [review]
Impressive research and documentation!

**Review by BradfordMez — APPROVED** [review]
Great research! Love the organization of the information!

**Pull request merged**
