### PR TITLE
Feature/header footer touchup

### PR DESCRIPTION
**Pull request by collerhatguy**
## Description
https://www.loom.com/share/0f270fc5b5014da080c358b70cf16031 
Header is now capable of logging out, includes a bookmarks button linking to the landing page, and is on every page except login page.

By:
- Romy Shockey
- Dharmik Savaliya
- Jacob Shomali
- Juliane Vo Nguyen
- Ryan ishimaru

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by tdubs42** [comment]
[Header Component](https://trello.com/c/oLFAGh4O/73-header-component)

**Review by JLeegwater — APPROVED** [review]
Looks good! Yea the footer was deleted and it just waiting on merge!

**Review by tdubs42 — APPROVED** [review]
Great teamwork and being proactive on the logout functionality! @paulstgermain I've gone ahead and cleared the merge conflicts on this PR so we can get it merged straight away :smile:

**Review by makeityourself121 — APPROVED** [review]
Great job!

**Review by rishimaru23 — APPROVED** [review]
Great work Jacob!

**Comment by tdubs42** [comment]
[Add a "bookmarks" button in the Header](https://trello.com/c/NIN2F8TP/89-add-a-bookmarks-button-in-the-header)

**Review by crayburn18 — APPROVED** [review]
Looks good clean code.

**Review by Andrewschaer — COMMENTED** [review]
Great work here improving the header!  Really like the consolidation and cleanup of the import statements (future cohorts will be able to get up to speed with ease!).  Also great work connecting the logout button to Okta... truly a big feature of getting to an MVP state.

**Pull request merged**
