### PR TITLE
Bug/double header

### PR DESCRIPTION
**Pull request by makeityourself121**
## Description

There was a bug causing the landing page to have a double header. We found the bug in the RenderLandingPage component. We removed the Header from the div, which removed the second header. 

Fixed the issue of having a double header on the landing page.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

## Contributors: 

-Dharmik Savaliya
-Rimsha Saleem
-Cara Locke
-Bailey Evanger

## Loom Video:
https://www.loom.com/share/a16cdc4d30ed4586bb3a9b9eae755131

### CODE REVIEW

**Comment by tdubs42** [comment]
[Remove double header](https://trello.com/c/zJZrtfse/103-remove-double-header)

**Review by JackOrth — APPROVED** [review]
Thanks for finding this bug. Great fix!

**Review by fervelgo — DISMISSED** [review]
Just to keep it clean, remove the Header from imports in line 2 :)

**Comment by caralocke** [comment]
> Just to keep it clean, remove the Header from imports in line 2 :)

Good catch! It looks like that change has been made now. Thank you!

**Review by BradfordMez — APPROVED** [review]
Good job fixing that header bug!

**Review by rishimaru23 — APPROVED** [review]

**Review by collerhatguy — APPROVED** [review]
Its ready spaghetti

**Review by rkshockey — APPROVED** [review]
Good catch cleaning up the imports as well.

**Review by JLeegwater — APPROVED** [review]
Great catch! Glad we could get this figured out!

**Review by fervelgo — APPROVED** [review]
Looking goooooood :)

**Review by Andrewschaer — COMMENTED** [review]
Great debugging work here!  Quick fix that made a big difference in making sure the UI is clean!  Great work removing the Header from the Import statement here as well.

**Pull request merged**
