### PR TITLE
Feature/bookmark icons

### PR DESCRIPTION
**Pull request by rkshockey**
## Description

Added the files for the new bookmark icons chosen by the group and implemented them in the Landing Card. Since these are pulled from a 3rd party source that requires they be attributed to the creator, I also made a small footer for that purpose.

The test document for the LandingCard component has been updated to reflect the changed icons.

https://www.loom.com/share/0347f35869944ab28a9ae86cc6bfbc6b

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by collerhatguy — APPROVED** [review]
Good attention to detail Romy! Most people would forget to adjust the tests.

**Review by makeityourself121 — APPROVED** [review]
You did a good job on changing the star to bookmark icon, and also included the links in the footer, way to go 😊

**Review by BradfordMez — APPROVED** [review]
Awesome work, especially going in and editing those tests to reflect the changes as well!

**Review by madina-iz — APPROVED** [review]
Great choice of icon style!

**Comment by Andrewschaer** [comment]
This was a great addition to the code base, helping to round out the form of our cards for the landing page by including the bookmarks.  Also want to echo the praise on updating the tests to reflect the changes.  Great attention to detail!

**Review by Andrewschaer — COMMENTED** [review]
This was a great addition to the code base, helping to round out the form of our cards for the landing page by including the bookmarks. Also want to echo the praise on updating the tests to reflect the changes. Great attention to detail!

**Pull request merged**
